name: Shell Command

on: [push]

jobs:
  run-shell-commnad:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hello World"
      - name: multiline
        run: |
          node -v